### ISSUE TITLE
Error in EmailMessage with MIMEBase attachment

### ISSUE THREAD

**Issue by yuvadm** [BradWhittington/django-mailgun#36]
An email message with alternative is built like so:

    email_message = EmailMultiAlternatives(subject, body, from_email, [to_email])
    email_message.attach_alternative(foo, 'text/html')
    email_message.mixed_subtype = 'related'
    email_message.attach(MIMEImage(image_fp.read()))
    email_message.content_subtype = "html"
    email_message.send()

When sent via mailgun the following error is given:

```
AttributeError("'int' object has no attribute 'lower'",)
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/django/core/mail/message.py
", line 303, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/django_mailgun.py", line 16
8, in send_messages
    if self._send(message):
  File "/opt/python/run/venv/local/lib/python2.7/site-packages/django_mailgun.py", line 13
7, in _send
    post_data.append(('attachment', (attachment[0], attachment[1],)))
  File "/usr/lib64/python2.7/email/message.py", line 294, in __getitem__
    return self.get(name)
  File "/usr/lib64/python2.7/email/message.py", line 360, in get
    name = name.lower()
AttributeError: 'int' object has no attribute 'lower'
```

The Django `attach()` API accepts both MIMEBase parameters as well as `(filename, content, mimetype)` triplets and it seems django-mailgun doesn't support the former.

**Comment by x007007007** [comment]
hi, https://github.com/BradWhittington/django-mailgun/pull/37 may be helpful.

**Comment by pydanny** [comment]
This project is unsupported. Please use https://github.com/anymail/django-anymail instead.
